### ISSUE TITLE
When is Pop method called?

### ISSUE THREAD

**Issue by Pawnr** [shalskar/PeekAndPop#16]
PeekAndPop peekAndPop = new PeekAndPop.Builder(this)
                .peekLayout(R.layout.peek_view)
                .longClickViews(ImageView)
                .build();

So when i longClick my ImageView, it calls the Peek function, which layout has just an other ImageView with a background color, but my screen stuck there, and cant do anything else?
http://i67.tinypic.com/120rzu9.png

**Comment by shalskar** [comment]
Is the ImageView located within a scrollable view? If so you will need to add .parentViewGroupToDisallowTouchEvents() with the parent scrollable view. 

If this isn't the case, try using the debugger to check if the peek view is receiving a cancel or up touch event, as this usually triggers the peek view to pop().

**Comment by Pawnr** [comment]
No it`s not located within a scrollable view, "peek_view layout" is just a RelativeLayout, with the ImageView.
I`ll try the second answer as soon as i can, and let you know.

**Comment by JitenNumberTank** [comment]
Hello shalskar,

I have also got this issue. My issue is same like that. I still facing this issue.

**Comment by shalskar** [comment]
OK, do you have your code here on Github that I could look at? Does this happen each time you use touch the peek view or only every now and then?

JitenNumberTank, did you still have the same problem even after trying the new branch?

**Comment by JitenNumberTank** [comment]
yes after trying new branch. I am still getting this issue. I found this is found specially when you lock your device and unlock device. then use this peek and pop functinality. pop method called but view stucked there. not being invisible after that.

**Comment by JitenNumberTank** [comment]
yes after trying new branch. I am still getting this issue. I found this is
found specially when you lock your device and unlock device. then use this
peek and pop functinality. pop method called but view stucked there. not
being invisible after that.

On Mon, Jun 6, 2016 at 2:48 PM, Vincent Te Tau notifications@github.com
wrote:

> OK, do you have your code here on Github that I could look at? Does this
> happen each time you use touch the peek view or only every now and then?
> 
> JitenNumberTank, did you still have the same problem even after trying the
> new branch?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/shalskar/PeekAndPop/issues/16#issuecomment-223907943,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANb0Tu25wPX56H_yup_YdJcNlX3OChY1ks5qI-XmgaJpZM4IucNB
> .

## 

```
       Thanks & Regards,
```

*Jiten Ramoliya *

**Comment by JitenNumberTank** [comment]
hello shalskar,
Do you have any forked user who make this library better after forking and get more star? If you have then suggest me so I can check difference there and rectify this issue

**Comment by JitenNumberTank** [comment]
Hello shalskar,

I am still getting same issue. Could you get rid of this ridiculous bug?

**Comment by shalskar** [comment]
Can you please comment on the open issue that you created, rather than this one.

**Comment by JitenNumberTank** [comment]
okay
