### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by vinjex** [shalskar/PeekAndPop#25]
I wasn't able to use your library, so I checked on jitpack and found that:
`compile 'com.github.shalskar:PeekAndPop:v1.1.0'`
should be:
`compile 'com.github.shalskar:PeekAndPop:1.1.0'`
Check [this on jitpack](https://jitpack.io/#shalskar/PeekAndPop/1.1.0)
Nice library by the way!

**Comment by shalskar** [comment]
Hey thanks for finding this, I've made the change
