### ISSUE TITLE
Not able to install v1.1.0

### ISSUE THREAD

**Issue by skined90** [shalskar/PeekAndPop#26]
What am I doing wrong. I was using v1.0.1 and now I've seen there is a newer version v1.1.0 but I'm not able to install it. I'm getting the error:

> Error:(59, 13) Failed to resolve: com.github.shalskar:PeekAndPop:v1.1.0

**Comment by shalskar** [comment]
HI, it seems Jitpack have slightly changed their versioning schema, try this:

compile 'com.github.shalskar:PeekAndPop:1.1.0'

**Comment by PravinewA** [comment]
implementation 'com.github.shalskar:PeekAndPop:1.1.0' doesnot work. Is there any new version, I am not able to install it.
Failed to resolve : 'com.github.shalskar:PeekAndPop:1.1.0'
