### ISSUE TITLE
onTouch move ImageView inside PeekView

### ISSUE THREAD

**Issue by AngleV** [shalskar/PeekAndPop#9]
@shalskar 

By now PeekView is 1:1 ratio
So If you have an image with different ratio it would be a nice feature if user is able to hold and move the image inside PeekView by axis XY

**Comment by shalskar** [comment]
The layout resource you provide can specify any size you want the PeekView to be, it doesn't even have to contain an image view.

However you could implement your feature by extending the PeekAndPop class and overriding the initialiseGestureListener(), supplying your own PeekAndPopOnTouchListener (you would need to extend this yourself too). 

This would allow you to receive the touch events and use them to move the image view.

**Comment by AngleV** [comment]
something like this ?

```
public class MyPeekAndPop extends PeekAndPop {
    public MyPeekAndPop(Builder builder) {
        super(builder);
    }


    @Override
    protected void initialiseGestureListener(@NonNull View view, int position) {
        view.setOnTouchListener(new MyOnTouchListener(position));
    }
}
```

**Comment by shalskar** [comment]
Yeah that should work, as long as MyOnTouchListener extends PeekAndPopOnTouchListener and you call super() in the the onTouch() method.

**Comment by AngleV** [comment]
can not extend PeekAndPopOnTouchListener. Its a private class

**Comment by shalskar** [comment]
Changed it to protected.

Here you go:

compile 'com.github.shalskar:PeekAndPop:0e2ee57398'

**Comment by AngleV** [comment]
i think i am missing something here..
Still can't extend it.
Error:(16, 56) error: PeekAndPop.PeekAndPopOnTouchListener has protected access in PeekAndPop

**Comment by shalskar** [comment]
Something like this:

public class MyPeekAndPop extends PeekAndPop {

```
public MyPeekAndPop(Builder builder) {
    super(builder);
}

@Override
protected void initialiseGestureListener(@NonNull View view, int position) {
    view.setOnTouchListener(new MyPeekAndPopOnTouchListener(position));
}

protected class MyPeekAndPopOnTouchListener extends PeekAndPopOnTouchListener{

    public MyPeekAndPopOnTouchListener(int position) {
        super(position);
    }

    @Override
    public boolean onTouch(final View view, MotionEvent event) {
        boolean result = super.onTouch(view, event);

        // Do stuff here

        return result;
    }
}

public static class Builder extends PeekAndPop.Builder{

    public Builder(@NonNull Activity activity) {
        super(activity);
    }

    @Override
    public MyPeekAndPop build() {
        if (peekLayoutId == -1) {
            throw new IllegalArgumentException("No peekLayoutId specified.");
        }
        return new MyPeekAndPop(this);
    }
}
```

}

Use this commit instead as I had to change the PeekAndPopOnTouchListener class to be non-final:

compile 'com.github.shalskar:PeekAndPop:2ce6379591'

**Comment by AngleV** [comment]
@shalskar 
Yes now it works but i can't figure out how to access my imageview inside onTouch method

**Comment by shalskar** [comment]
There are many ways you could do this but the simplest to me is:

public class MyPeekAndPop extends PeekAndPop {

```
private ImageView imageView;

public MyPeekAndPop(Builder builder) {
    super(builder);
    imageView = (ImageView) peekView.findViewById(R.id.image_view);
```

   }
...
}

**Comment by AngleV** [comment]
@shalskar 

What i have done so far

```
        @Override
        public boolean onTouch(final View view, MotionEvent event) {
            boolean result = super.onTouch(view, event);

            final int x = (int) event.getX();
            final int y = (int) event.getY();
            matrix.reset();
            matrix.postTranslate(x, y);
            imageView.setScaleType(ImageView.ScaleType.MATRIX);
            imageView.setImageMatrix(matrix);

            return result;
        }
```

That works and the image is moving but the x and y is from recyclerview touch and not from my imageview. What i need is to set the x and y to the center of imageview. user should be able to move by xy the image inside the container.

Any clue ?

**Comment by shalskar** [comment]
Have you set parentViewGroupToDisallowTouchEvents(recyclerView)?

**Comment by AngleV** [comment]
Yes !

```
        peekAndPop = new MyPeekAndPop.Builder(getActivity())
                .blurBackground(shouldBlur)
                .peekLayout(R.layout.peek_view)
                .parentViewGroupToDisallowTouchEvents(mRecyclerView)
                .build();
```

but no luck

**Comment by shalskar** [comment]
OK I see what you're trying to do. The x,y coordinates will be relative to the view that was long clicked.
Due to the nature of PeekAndPop (whole transaction occurs within one long click) we have to receive the touch events from the view that was long clicked. 

This means you'll have to do some calculations to get the correct x,y coordinates.

`event.getX() + view.getX()`
`event.getY() + view.getY()`

will give you the original coordinates of the touch event or you can use

`event.getRawX()`
`event.getRawY()`

to get the exact coordinates of the touch event.

**Comment by AngleV** [comment]
@shalskar 
In fact what i am trying to do is the following
1. User holds a recyclerview item with an image inside.
2. PeekAndPop shows up 
3. Now two things can happen. If image width is bigger than peekView = 320dp user can drag the image only to x coordinate.
4. if image height is bigger than peekView = 320dp user can drag the image only to y coordinate.

here i must say that image inside the imageview is centered both vertically and horizontally

```
@Override
        public boolean onTouch(final View view, MotionEvent event) {
            boolean result = super.onTouch(imageView, event);



            switch(event.getAction() & MotionEvent.ACTION_MASK) {
                case MotionEvent.ACTION_DOWN: {
                    savedMatrix.set(matrix);
                    start.set(event.getRawX(), event.getRawY());
                    drag = true;
                    }
                    break;


                case MotionEvent.ACTION_MOVE: {

                    if(drag) {

                        matrix.set(savedMatrix);

                        matrix.getValues(matrixValues);
                        matrixX = matrixValues[2];
                        matrixY = matrixValues[5];
                        if (imageView.getDrawable() != null) {
                            width = matrixValues[0] * imageView.getDrawable().getIntrinsicWidth();
                            height = matrixValues[4] * imageView.getDrawable().getIntrinsicHeight();
                        }

                        dx = event.getX() + imageView.getX() - start.x;
                        dy = event.getY() + imageView.getY() - start.y;

                    //if image will go outside left bound
                    if (matrixX + dx < 0){
                        dx = -matrixX;
                    }
                    //if image will go outside right bound
                    if(matrixX + dx + width > imageView.getWidth()){
                        dx = imageView.getWidth() - matrixX - width;
                    }
                    //if image will go oustside top bound
                    if (matrixY + dy < 0){
                        dy = -matrixY;
                    }
                    //if image will go outside bottom bound
                    if(matrixY + dy + height > imageView.getHeight()){
                        dy = imageView.getHeight() - matrixY - height;
                    }
                        matrix.postTranslate(dx, dy);
                        imageView.setScaleType(ImageView.ScaleType.MATRIX);
                        imageView.setImageMatrix(matrix);
                    }

                }
                break;
                case MotionEvent.ACTION_UP: {
                    drag = false;
                }
                    break;
            }
            return result;
        }
```

so far it does not work so well

**Comment by shalskar** [comment]
Can you put this in a repo and give me a link? I'll have a play with it but I don't think the library would be preventing it from working.
